# PLACEHOLDER: replace all `age1...` recipients with real public Age keys
# before encrypting any file with `sops`.
keys:
  #- &admin_myuser age1replacewithyouradminpublickeyxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - &nixhael age1gqzvzd2ewvta5grp3whe2a5tsd463rg6n2l059alrdnq8thcjdrsu07ced
  - &nixspo age1tqaq3s7vzncvp3dr4kefwmltfw40423w6t58f43snmqdfmwjxe0qafsdhw
  - &homelab age1ahgql6pf0yszr50kt5c8nsvqzh5ssl8ldxmpfpr2nfe2kdw7kdsqvcz36w
  - &backup age1ctrh545yzm2y5v6rmn5adrpmtnqpprqnk6g99pdu7nn7zchw2g6qy0eeqz

creation_rules:
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          #- *admin_myuser
          - *nixhael
          - *nixspo
          - *backup

  - path_regex: secrets/nixhael\.yaml$
    key_groups:
      - age:
          #- *admin_myuser
          - *nixhael
          - *backup

  - path_regex: secrets/nixspo\.yaml$
    key_groups:
      - age:
          #- *admin_myuser
          - *nixspo
          - *nixhael
          - *backup

  - path_regex: secrets/homelab\.yaml$
    key_groups:
      - age:
          #- *admin_myuser
          - *homelab
          - *nixspo
          - *backup

  - path_regex: secrets/home34b\.yaml$
    key_groups:
      - age:
          #- *admin_myuser
          - *nixspo
          - *nixhael
          - *backup

  - path_regex: secrets/users/xsnilzx\.yaml$
    key_groups:
      - age:
          - *homelab
          - *nixhael
          - *nixspo
          - *backup
