# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];

    kernel.sysctl = {
      "vm.swappiness" = 10;
      "vm.dirty_ratio" = 15;
      "vm.dirty_background_ratio" = 5;
      "vm.vfs_cache_pressure" = 50;
    };
    kernelParams = [
      "intel_pstate=active"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/13ac6e00-6539-4c47-b3ec-f969427d62d1";
    fsType = "ext4";
    options = [
      "noatime" # Weniger Writes → SSD schonen
      "data=ordered" # Sicher, bewährter Standard
      "errors=remount-ro" # Schutz bei Filesystem-Fehler
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C924-69AC";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/086e5702-865f-4881-836a-eb6c1020c8bc";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
